# Revisión de código para 2.2 One-sided Jacobi numerical aproximación

**Fecha:** 13 de Abril de 2020

**Responsable de revisión:** León Garay (Test 1 al 4) y Dorely Morales (Test 5 y 6)

**Código revisado**

In [1]:
indices <- function(n) {
  # Crea una lista de tamaño (n-1)n/2 con pares de índices de la siguiente
  #  manera: (1,2),..,(1,n),(2,3),..,(2,n),...,(n-1,n)
  # Args: 
  #    n: número entero postivo 
  #       se refiere al número de columnas
  #Returns:
  #    lista con pares de índices
    a <- NULL
    b <- NULL
    indices <- NULL
    for (i in 1:(n-1)){
    a <- append(a,rep(i,n-i))
    b <- append(b,seq(i+1,n))    
    }
    for(i in 1:round(n*(n-1)/2))
    indices[[i]] <- list(c(a[i], b[i]))
    indices
}

In [2]:
ortogonal <- function(u,v,TOL=10^-8){
  # Verifica si dos vectores son ortogonales, arrojando un 1 si lo es, y un 0 si no lo es.
  # Args: 
    # u, v como vectores de la misma dimensión.Y un valor real de tolerancia TOL(10^-8).
    # Nota: Se sugiere una TOL mayor a 10^-32.
  # Returns: 
    # Valor booleano 0 (no son ortongoales), 1 (son ortogonales)
    if ( norm(u,type ="2") < TOL | norm(v,type ="2") < TOL){
        ret<-0
    } else{ 
        
        if( (u%*%v)  /(norm(u,type ="2")*norm(v,type ="2")) < TOL   ){
    ret<-1
  }
  else{
    ret<-0
  }       
    }
  ret
}

In [3]:
signo<-function(x) {
  # Indica el signo de un número x
  # Args: 
  #    x (numeric): número a revisar
  # Returns:
  #    1 si el número es positivo o cero
  #    -1 si el número es negativo
  
  ifelse(x<0,-1,1)
  }

In [4]:
solver <- function(U,S,V,b){
    # Construye la solución de un sistema de ecuaciones a partir de matrices 
    # U, S, V, y vector b. Se asume que S es diagonal. 
    # Para ello resuelve S d = U^Tb, para construir x=Vd.
    # Notas:
    # 1) Se utilizó la función backsolve para resolver el sistema triangular.
    # 2) Al ser S diagonal, es indistinto si usar un solver para matrices traingulares inferiores o superiores.
    # Args: 
    #  	    U (mxm),V(nxn), S(mxn) matriz diagonal y b (m) un vector.
    # Returns: 
    #      x vector (m)
  d = backsolve(S, t(U)%*%b)
  x = V%*%d
  return(x)
}

In [5]:
svd_jacobi_aprox <- function(A,TOL,maxsweep){
    # Función que calcula la descomposición de una matriz A en sus componentes U, S V, 
    # utilizando el método de Jacobi para calcular la factorización SVD.De esta forma 
    # la matriz A queda descompuesta de la siguiente forma: A = U*S*t(V).
    # Args: 
    #    A (matriz): Matriz de entrada (nxm) de números reales a la que se le calculará la descomposición SVD.
    #    TOL (numeric): controla la convergencia del método, siendo un valor real de 10^-8 (sugerido en la nota 3.3.d.SVD)
    #    Nota: Se sugiere una TOL mayor a 10^-32.
    #    maxsweep (numeric): número máximo de sweeps,donde cada sweep consiste de un número máximo(nmax)
    #    de rotaciones; y en cada sweep se ortogonalizan 2 columnas.
    # Returns: 
    #   Lista con 3 elementos, donde el primer elemento representan a las matriz S(mxm) matriz diagonal,el segundo a la matriz U(nxm)
    #   y el tercero y último a la matriz V (mxm).En conjunto estas tres matrices componen la factorización SVD de la matriz de entrada A.
    
    #dimensiones
    n<-dim(A)[2] #numero de columnas
    m<-dim(A)[1] #numero de filas
    nmax<-n*(n-1)/2

    #inicialza valores del ciclo
    ak<-A
    vk<-diag(n)
    sig <- NULL
    uk <- ak
    num_col_ortogonal<-0
    k<-0

    while(k<=maxsweep & num_col_ortogonal<nmax){
    num_col_ortogonal<-0
    ind <- indices(n)
    for(i in 1:nmax){
      col_j<-ak[,ind[[i]][[1]][2]]
      col_i<-ak[,ind[[i]][[1]][1]]
    
      #comprueba ortogonalidad  
      if(ortogonal(col_i,col_j,TOL)==1){
        num_col_ortogonal<-num_col_ortogonal+1
      }
      else{
        #calcula coeficientes de la matriz
        a<-sum(col_i*col_i)
        b<-sum(col_j*col_j)
        c<-col_i%*%col_j
        
        if(c<TOL){break}
        #calcula la rotacion givens que diagonaliza
        epsilon<-(b-a)/(2*c)
        t<-signo(epsilon)/(abs(epsilon)+sqrt(1+epsilon**2))
        cs<-1/sqrt(1+t**2)
        sn<-cs*t
        
        #actualiza las columnas de la matriz ak
        for(l in seq(1,m)){
          temp<-ak[l,ind[[i]][[1]][1]]
          ak[l,ind[[i]][[1]][1]]<-cs*temp-sn*ak[l,ind[[i]][[1]][2]]
          ak[l,ind[[i]][[1]][2]]<-sn*temp+cs*ak[l,ind[[i]][[1]][2]]
        }
        
        #actualiza las columnas de la matriz vk
        for(l in seq(1,n)){
          temp<-vk[l,ind[[i]][[1]][1]]
          vk[l,ind[[i]][[1]][1]]<-cs*temp-sn*vk[l,ind[[i]][[1]][2]]
          vk[l,ind[[i]][[1]][2]]<-sn*temp+cs*vk[l,ind[[i]][[1]][2]]
        
        }
       }
  }
  k<-k+1
 }
    #Obtener sigma
        for(i in 1:n){
        sig<- append(sig,norm(ak[,i],type ="2"))
    }

    #Obtener U
    for(i in 1:n){
        if (sig[i]<TOL){
            uk[,i]<-0  
        } else{
        uk[,i] <- ak[,i]/sig[i]
        }
    }

    # Indices de sigma ordenada en forma decreciente para ordenar V,S,U
    index <- order(sig,decreasing = TRUE)
    vk <- vk[,index]
    S <- diag(sig[index])
    uk <- uk[,index]

    list(S = S, U = uk, V= vk)
 }   

In [6]:
sel_solver<-function(A,b,TOL=10**-8,maxsweep=20){
    #Función resuelve un sistema de ecuaciones lineales (SEL) utilizando la descomposición SVD
    #por medio del método de One-sided Jacobi 
    #El SEL es de la forma Ax=b
    # Args: 
    #    A (float): matriz de incógnitas del SEL
    #    b (float): vector de igualdada del sistema
    #    TOL (numeric): controla la convergencia del método
    #    maxsweep (int): número máximo de sweeps 
    #Returns: x (float): vector solución 

    svd<-svd_jacobi_aprox(A,TOL,maxsweep)
    x<-solver(svd$U,svd$S,svd$V,b)
    x
}

**1.Sobre la documentación del código/de la función**

¿Se encuentran presentes en la implementación los siguientes elementos? Por favor, ingrese explicaciones detalladas.

**a) Descripción concisa y breve de lo que hace el código/la función**

La función de encuentra bien documentada.

**b) Descripción de sus argumentos de entrada, su significado y rango de valores que pueden tomar**

Parcialmente, se sugiere complementar la descripción de los argumentos de entrada especificando que A tiene que ser una matriz de números reales de dimensión nxm. Además, A es una matriz de coeficientes del sistema (en lugar de incógnitas) para SEL. Y hay que corregir un typo en la descripción de b: "#    b (float): vector de igualdad o lado derecho del sistema"

**c) Descripción de los tipos de argumentos de entrada y de salida (por ejemplo, valores enteros, reales, strings, dataframe, matrices, etc)**

Sí se encuentra bien documentado.

**d) Descripción de la salida de la función, su significado y valores/objetos que deben regresar**

Parcialmente, se sugiere complementar la descripción del argumento de salida especificando que x es de tamaño n.

**2. Cumplimiento de objetivos del código/de la función**

**a) ¿El código cumple los objetivos para los que fue diseñado?**

Sí dado que genera un vector x.

**b) ¿La salida de la función genera el valor necesario?**

Parcialmente, es necesario corregir algunos errores que ocurren cuando se introduce una matriz A de mxn con todos sus elementos aij iguales a un mismo valor constante. Adicionalmente, se necesita hacer optimizaciones a la función ya que para matrices A de tamaño mediano no encuentra la SVD.

**3. Pruebas**

Ocupe la presente sección para hacer diseño de pruebas variando los parámetros que recibe el código la función en diferentes rangos para evaluar su comportamiento y/o detectar posibles fallos


**Test 1**

**Objetivo del test 1:** Verificar que la función se comporta correctamente para una matriz nula A de mxn.

**Implementación del test 1:**

In [7]:
c5 <- rep(0,25)
b5 <- c(7,1,33,24,-49)
A5 <- matrix(c5, nrow=5, ncol=5, byrow = T)
c4 <- rep(0,16)
b4 <- c(15,-6,17,-7)
A4 <- matrix(c4, nrow=4, ncol=4, byrow = T)
c3 <- rep(0,9)
b3 <- c(2,9,-5)
A3 <- matrix(c3, nrow=3, ncol=3, byrow = T)
c2 <- rep(0,4)
A2 <- matrix(c2, nrow=2, ncol=2, byrow = T)
b2 <- c(2,9)

TOL<-10**-8
maxsweep<-20

print(A2)
print(A3)
print(A4)
print(A5)
#x_sel1<-sel_solver(A1,b1,TOL = 10**-15,maxsweep=10000)

     [,1] [,2]
[1,]    0    0
[2,]    0    0
     [,1] [,2] [,3]
[1,]    0    0    0
[2,]    0    0    0
[3,]    0    0    0
     [,1] [,2] [,3] [,4]
[1,]    0    0    0    0
[2,]    0    0    0    0
[3,]    0    0    0    0
[4,]    0    0    0    0
     [,1] [,2] [,3] [,4] [,5]
[1,]    0    0    0    0    0
[2,]    0    0    0    0    0
[3,]    0    0    0    0    0
[4,]    0    0    0    0    0
[5,]    0    0    0    0    0


In [8]:
x_sel2 <- sel_solver(A2,b2,TOL,maxsweep)
#x_sel3 <- sel_solver(A3,b3,TOL,maxsweep)
#x_sel4 <- sel_solver(A4,b4,TOL,maxsweep)
#x_sel5 <- sel_solver(A5,b5,TOL,maxsweep)

ERROR: Error in backsolve(S, t(U) %*% b): singular matrix in 'backsolve'. First zero in diagonal [1]


**Principales hallazos del test 1**

La función arroja un error pues existen infinitas soluciones que satisfacen A=U*S*V^T. Esto debido a que si tomamos la matriz S nula de mxn y cualesquiera matrices U de mxm y V de nxn ortogonales tenemos una solución.

**Test 2**

**Objetivo del test 2:** Verificar que la función se comporta correctamente para una matriz no nula A de mxn con entradas constantes.

**Implementación del test 2:**

In [9]:
cte <- 5
c5 <- rep(cte,25)
b5 <- c(7,1,33,24,-49)
A5 <- matrix(c5, nrow=5, ncol=5, byrow = T)
c4 <- rep(cte,16)
b4 <- c(15,-6,17,-7)
A4 <- matrix(c4, nrow=4, ncol=4, byrow = T)
c3 <- rep(cte,9)
b3 <- c(2,9,-5)
A3 <- matrix(c3, nrow=3, ncol=3, byrow = T)
c2 <- rep(cte,4)
A2 <- matrix(c2, nrow=2, ncol=2, byrow = T)
b2 <- c(2,9)

TOL<-10**-8
maxsweep<-20

print(A2)
print(A3)
print(A4)
print(A5)
#x_sel1<-sel_solver(A1,b1,TOL = 10**-15,maxsweep=10000)

     [,1] [,2]
[1,]    5    5
[2,]    5    5
     [,1] [,2] [,3]
[1,]    5    5    5
[2,]    5    5    5
[3,]    5    5    5
     [,1] [,2] [,3] [,4]
[1,]    5    5    5    5
[2,]    5    5    5    5
[3,]    5    5    5    5
[4,]    5    5    5    5
     [,1] [,2] [,3] [,4] [,5]
[1,]    5    5    5    5    5
[2,]    5    5    5    5    5
[3,]    5    5    5    5    5
[4,]    5    5    5    5    5
[5,]    5    5    5    5    5


In [10]:
x_sel2 <- sel_solver(A2,b2,TOL,maxsweep)
#x_sel3 <- sel_solver(A3,b3,TOL,maxsweep)
#x_sel4 <- sel_solver(A4,b4,TOL,maxsweep)
#x_sel5 <- sel_solver(A5,b5,TOL,maxsweep)

ERROR: Error in backsolve(S, t(U) %*% b): singular matrix in 'backsolve'. First zero in diagonal [2]


**Principales hallazos del test 2**

La función arroja un error pues existen infinitas soluciones que satisfacen A=U*S*V^T. Esto debido a que si tomamos la matriz S nula de mxn y cualesquiera matrices U de mxm y V de nxn ortogonales tenemos una solución.

**Test 3**

**Objetivo del test 3:** Verificar que la función se comporta correctamente para una matriz A de nxn con n = 2,3,4,5.

**Implementación del test 3:**

In [11]:
c5 <- c(2,-1,4,1,-1,-1,3,-2,-1,2,5,1,3,-4,1,3,-2,-2,-2,3,-4,-1,-5,3,-4)
b5 <- c(7,1,33,24,-49)
A5 <- matrix(c5, nrow=5, ncol=5, byrow = T)
c4 <- c(1,-2,2,-3,3,4,-1,1,2,-3,2,-1,1,1,-3,-2)
b4 <- c(15,-6,17,-7)
A4 <- matrix(c4, nrow=4, ncol=4, byrow = T)
c3 <- c(2,-1,1,3,1,-2,-1,2,5)
b3 <- c(2,9,-5)
A3 <- matrix(c3, nrow=3, ncol=3, byrow = T)
c2 <- c(2,-3,5,2)
A2 <- matrix(c2, nrow=2, ncol=2, byrow = T)
b2 <- c(2,9)

TOL<-10**-8
maxsweep<-20

print(A2)
print(A3)
print(A4)
print(A5)
#x_sel1<-sel_solver(A1,b1,TOL = 10**-15,maxsweep=10000)

     [,1] [,2]
[1,]    2   -3
[2,]    5    2
     [,1] [,2] [,3]
[1,]    2   -1    1
[2,]    3    1   -2
[3,]   -1    2    5
     [,1] [,2] [,3] [,4]
[1,]    1   -2    2   -3
[2,]    3    4   -1    1
[3,]    2   -3    2   -1
[4,]    1    1   -3   -2
     [,1] [,2] [,3] [,4] [,5]
[1,]    2   -1    4    1   -1
[2,]   -1    3   -2   -1    2
[3,]    5    1    3   -4    1
[4,]    3   -2   -2   -2    3
[5,]   -4   -1   -5    3   -4


In [12]:
x_sel2 <- sel_solver(A2,b2,TOL,maxsweep)
x_sel3 <- sel_solver(A3,b3,TOL,maxsweep)
x_sel4 <- sel_solver(A4,b4,TOL,maxsweep)
x_sel5 <- sel_solver(A5,b5,TOL,maxsweep)

Buscamos que la función nos regrese aproximadamente $b2 = (2,9) $

In [13]:
A2%*%x_sel2

[,1]
[1,] 2   
[2,] 9

Podemos ver que funcionó correctamente, ya que Ax=b.

Ahora probaremos con $A_{3x3}$ buscamos $b3 = (2,9,-5)$

In [14]:
A3%*%x_sel3

[,1]     
[1,]  2.327966
[2,] 11.280633
[3,] -8.629119

En este caso podemos ver que la función no arrojó correctamente los valores de Ax=b.

Seguimos con el caso $A_{4x4}$ y buscamos que $b4 = (15,-6,17,-7)$

In [15]:
A4%*%x_sel4

[,1]      
[1,]  22.127278
[2,] -12.551705
[3,]  23.677302
[4,]  -8.309975

Podemos observar que tampoco arrojó balores cercanos de Ax=b.

Finalmente probaremos con $A-{5x5}$ y buscamos $b5 = (7,1,33,24,-49)$

In [16]:
A5%*%x_sel5

[,1]      
[1,]   1.013013
[2,]  10.506870
[3,]  62.822134
[4,]  39.049742
[5,] -84.244898

Podemos observar que tampoco arrojó valores correctos.

**Principales hallazos del test 3**

La función arroja valores lejamos a los esperados para matrices con dimensiones mayores a 2x2.

**Test 4**

**Objetivo del test 4:** Verificar que la función se comporta correctamente para una matriz A de mxn con n = 2,3,4,5 y m = 2,3,4.

**Implementación del test 4:**

In [17]:
c5 <- c(2,-1,4,1,-1,-1,3,-2,-1,2,5,1,3,-4,1,3,-2,-2,-2,3)
b5 <- c(7,1,33,24,-49)
A5 <- matrix(c5, nrow=5, ncol=4, byrow = T)
c4 <- c(1,-2,2,-3,3,4,-1,1,2,-3,2,1)
b4 <- c(15,-6,17,-7)
A4 <- matrix(c4, nrow=4, ncol=3, byrow = T)
c3 <- c(2,-1,1,3,1,-2)
b3 <- c(2,9,-5)
A3 <- matrix(c3, nrow=3, ncol=2, byrow = T)
c2 <- c(2,-3,5,2)
A2 <- matrix(c2, nrow=2, ncol=2, byrow = T)
b2 <- c(2,9)

TOL<-10**-8
maxsweep<-20

print(A2)
print(A3)
print(A4)
print(A5)
#x_sel1<-sel_solver(A1,b1,TOL = 10**-15,maxsweep=10000)

     [,1] [,2]
[1,]    2   -3
[2,]    5    2
     [,1] [,2]
[1,]    2   -1
[2,]    1    3
[3,]    1   -2
     [,1] [,2] [,3]
[1,]    1   -2    2
[2,]   -3    3    4
[3,]   -1    1    2
[4,]   -3    2    1
     [,1] [,2] [,3] [,4]
[1,]    2   -1    4    1
[2,]   -1   -1    3   -2
[3,]   -1    2    5    1
[4,]    3   -4    1    3
[5,]   -2   -2   -2    3


In [18]:
x_sel2 <- sel_solver(A2,b2,TOL,maxsweep)
x_sel3 <- sel_solver(A3,b3,TOL,maxsweep)
x_sel4 <- sel_solver(A4,b4,TOL,maxsweep)
x_sel5 <- sel_solver(A5,b5,TOL,maxsweep)

Buscamos que la función nos regrese aproximadamente $b2 = (2,9) $

In [19]:
A2%*%x_sel2

[,1]
[1,] 2   
[2,] 9

Podemos ver que funcionó correctamente, ya que Ax=b.

Ahora probaremos con $A_{3x3}$ buscamos $b3 = (2,9,-5)$

In [20]:
A3%*%x_sel3

[,1]      
[1,]  0.1666667
[2,]  8.8333333
[3,] -3.6666667

En este caso podemos ver que la función no arrojó correctamente los valores de Ax=b.

Seguimos con el caso $A_{4x4}$ y buscamos que $b4 = (15,-6,17,-7)$

In [21]:
A4%*%x_sel4

[,1]       
[1,]  19.2029412
[2,]  -5.6382353
[3,]   0.5911765
[4,] -11.7852941

Podemos observar que tampoco arrojó balores cercanos de Ax=b.

Finalmente probaremos con $A-{5x5}$ y buscamos $b5 = (7,1,33,24,-49)$

In [22]:
A5%*%x_sel5

[,1]      
[1,]  27.976974
[2,]  11.503845
[3,]  18.094858
[4,]   8.093239
[5,] -37.052412

Podemos observar que tampoco arrojó valores esperados.

**Principales hallazos del test 4**

La función arroja valores lejanos a los esperados para matrices con dimensiones mayores a 2x2.


**Test 5**

**Objetivo del test 5:** Verificar que la función se comporta correctamente para matrices A de $10^2 \times 10^2$ **pseudoaleatorias** y un sistema homogéneo.

**Implementación del test 5:**

Para la creación de matrices pseudoaleatorias, haremos uso del paquete **mlsjunkgen** que dado un conjunto de input seeds: w,x,y,z genera matrices de números pseudo-aleatorios entre 0 y 1.

In [7]:
install.packages("mlsjunkgen",lib="/usr/local/lib/R/site-library/",
                repos="https://cran.itam.mx/",verbose=TRUE)

system (cmd0): /usr/lib/R/bin/R CMD INSTALL

foundpkgs: mlsjunkgen, /tmp/RtmpfyICEk/downloaded_packages/mlsjunkgen_0.1.1.tar.gz

files: /tmp/RtmpfyICEk/downloaded_packages/mlsjunkgen_0.1.1.tar.gz

1): succeeded '/usr/lib/R/bin/R CMD INSTALL -l '/usr/local/lib/R/site-library' /tmp/RtmpfyICEk/downloaded_packages/mlsjunkgen_0.1.1.tar.gz'



In [8]:
library(mlsjunkgen)

In [9]:
w <- 1
x <- 5
y <- 3
z <- 4

n<-10**2

#Definimos A matriz pseudo-aleatoria de números entre 0 y 1 con 16 decimales 
A<-mlsjunkgenm(nrow = n, ncol = n, w = w, x = x, y = y, z = z, round = 16)
#Definimos b vector de ceros
b<-c(rep(0, len=n))
TOL<-10**-8
maxsweep<-20

In [10]:
#Función
x_sel <- sel_solver(A,b,TOL,maxsweep)

In [12]:
#Comprobamos que la solución x es correcta
Comp<-A%*%x_sel
all(Comp==b)

[1] TRUE

**Principales hallazos del test 5**

* La función arroja resultados correctos para el SEL propuesto.

**Test 6**

**Objetivo del test 6:** Verificar que la función se comporta correctamente para matrices A de $10^2 \times 10^2$ y $10^1 \times 10^1$ **pseudoaleatorias** y diferentes lados derechos.

**Implementación del test 6:**

In [13]:
w <- 1
x <- 5
y <- 3
z <- 4

n<-10**2

#Definimos A matriz pseudo-aleatoria de números entre 0 y 1 con 16 decimales 
A<-mlsjunkgenm(nrow = n, ncol = n, w = w, x = x, y = y, z = z, round = 16)
TOL<-10**-8
maxsweep<-20
A

[,1]        [,2]        [,3]       [,4]        [,5]       [,6]      
 [1,] 0.847093986 0.36168442  0.77330303 0.77242522  0.63557536 0.38933633
 [2,] 0.746115227 0.73389915  0.55074111 0.86946199  0.86020675 0.46693459
 [3,] 0.436393491 0.54766020  0.95701550 0.55969012  0.12996766 0.98141020
 [4,] 0.003548722 0.39197078  0.06625749 0.84554358  0.96037845 0.27967929
 [5,] 0.262946911 0.05150537  0.75235196 0.85939965  0.70175734 0.21235088
 [6,] 0.324979464 0.90380362  0.85276315 0.50764604  0.31257446 0.97423442
 [7,] 0.622638935 0.54941419  0.88189912 0.86039902  0.71774556 0.31272255
 [8,] 0.118732307 0.68051559  0.76047701 0.48606880  0.99146612 0.63651436
 [9,] 0.733660081 0.52867955  0.85257220 0.18448507  0.19690196 0.04485164
[10,] 0.039080997 0.73732215  0.12979027 0.26085527  0.03380972 0.77457998
[11,] 0.971389061 0.93808306  0.25011178 0.62212096  0.96132187 0.59397176
[12,] 0.261765050 0.80932266  0.44651256 0.72269043  0.48331063 0.06315781
[13,] 0.746492613 0.15567685  0.01891482 0.64657198  0.22969843 0.16721579
[14,] 0.180259315 0.55322123  0.69595774 0.28702928  0.41862568 0.45993080
[15,] 0.554545199 0.45663607  0.83038490 0.96745603  0.13158317 0.55723482
[16,] 0.561715199 0.83248397  0.08767491 0.54843548  0.78084832 0.44256284
[17,] 0.129617045 0.13971409  0.79639145 0.77574434  0.25407090 0.84418674
[18,] 0.534053273 0.45788614  0.02308696 0.65878285  0.66595681 0.29330925
[19,] 0.982579836 0.81493023  0.08334665 0.38677351  0.31896274 0.94032741
[20,] 0.302642015 0.68487355  0.93060707 0.40094437  0.59554158 0.07946983
[21,] 0.864510360 0.76204609  0.19249924 0.27068361  0.09859011 0.44295626
[22,] 0.641709835 0.25729184  0.68977927 0.24202741  0.60657175 0.83517570
[23,] 0.507193009 0.48638286  0.51603689 0.92333445  0.08872773 0.12726458
[24,] 0.161585776 0.92185928  0.09666037 0.35269416  0.15056675 0.45951646
[25,] 0.354266485 0.55208116  0.47081117 0.04524306  0.01721888 0.68309036
[26,] 0.376784415 0.59271235  0.19321699 0.91873032  0.10248132 0.90342448
[27,] 0.415907996 0.48886942  0.53133224 0.65337935  0.04437433 0.58994848
[28,] 0.679549415 0.50662615  0.17512431 0.98527341  0.70465727 0.35085340
[29,] 0.101839912 0.25577182  0.22510939 0.28969145  0.54959336 0.32322209
[30,] 0.516642795 0.35309002  0.22554029 0.12757483  0.29388977 0.63347481
[31,] ⋮           ⋮           ⋮          ⋮           ⋮          ⋮         
[32,] 0.438944685 0.321324835 0.84279772 0.927622870 0.22466149 0.34500411
[33,] 0.056552321 0.799632612 0.67179221 0.038660897 0.29803538 0.38113396
[34,] 0.612099773 0.021365815 0.51954135 0.992243741 0.18904620 0.31079687
[35,] 0.603443788 0.111871647 0.06420440 0.419207513 0.14156963 0.22945644
[36,] 0.775671734 0.884057309 0.93639112 0.906222552 0.41280282 0.67646465
[37,] 0.298280690 0.151300737 0.28798480 0.533931743 0.01121821 0.21329037
[38,] 0.860343546 0.554385937 0.86231454 0.660752121 0.54689752 0.46267996
[39,] 0.538394625 0.451502710 0.78494212 0.425273661 0.37617363 0.83478716
[40,] 0.699020421 0.515962530 0.64351205 0.996400107 0.50388132 0.03150469
[41,] 0.005065657 0.392309247 0.19211982 0.747886914 0.93665641 0.18006464
[42,] 0.429801992 0.032801897 0.40663268 0.754481119 0.65105570 0.62929655
[43,] 0.055023609 0.374206835 0.62121112 0.634187500 0.70687949 0.95079227
[44,] 0.175793785 0.078358129 0.33164412 0.205439705 0.48241114 0.98088903
[45,] 0.234059336 0.915487493 0.01030417 0.330365467 0.21492943 0.16814193
[46,] 0.703730649 0.999254509 0.62419826 0.811847010 0.11271295 0.13380888
[47,] 0.591941778 0.419494233 0.58098671 0.134883310 0.75111527 0.73982019
[48,] 0.898734554 0.861598377 0.58078312 0.180911969 0.88962558 0.94698861
[49,] 0.477237702 0.343025331 0.21286075 0.895276870 0.53540217 0.91301568
[50,] 0.051174238 0.376102176 0.71251121 0.836798293 0.02261941 0.11152628
[51,] 0.080163975 0.000655535 0.67678053 0.063134068 0.80538036 0.23937150
[52,] 0.010052007 0.382996874 0.06948715 0.162618890 0.18994648 0.29122342
[53,] 0.841604548 0.045126244 0

In [19]:
#Definimos b vector de números aleatorios
set.seed(123)
b<-c(runif(n = n, min = -100, max = 100))

In [15]:
#Función
x_sel <- sel_solver(A,b,TOL,maxsweep)

**Sin embargo, en este caso Comp=Ax es diferente del vector b.**

In [16]:
#Comprobamos si la solución x es correcta
Comp<-A%*%x_sel
all(Comp==b)

[1] FALSE

In [25]:
#Verificamos que ninguno de los elementos de tamaño 100 coinciden
length(which(Comp != b))

[1] 100

**Notamos que los elementos de ambos vectores parecen coincidir respecto a su signo y las diferencias entre cada entrada parecieran mantenerse cercanas.**

In [28]:
head(Comp,10)
head(b,10)

[,1]      
 [1,] -58.708899
 [2,]  50.904351
 [3,] -23.058111
 [4,]  80.033017
 [5,]  82.579571
 [6,] -95.200730
 [7,]   1.827158
 [8,]  78.987237
 [9,]  14.143637
[10,] -13.340424

[1] -42.484496  57.661027 -18.204616  76.603481  88.093457 -90.888700
 [7]   5.621098  78.483809  10.287003  -8.677053

**Ahora reduciremos la dimensión de A por $10^1 \times 10^1$**

In [36]:
w <- 1
x <- 5
y <- 3
z <- 4

n<-10**1

#Definimos A matriz pseudo-aleatoria de números entre 0 y 1 con 16 decimales 
A<-mlsjunkgenm(nrow = n, ncol = n, w = w, x = x, y = y, z = z, round = 16)
TOL<-10**-8
maxsweep<-20
A

[,1]        [,2]      [,3]      [,4]       [,5]       [,6]      
 [1,] 0.847093986 0.9713891 0.8645104 0.28206127 0.78764684 0.45964341
 [2,] 0.746115227 0.2617650 0.6417098 0.70219179 0.36677052 0.52111346
 [3,] 0.436393491 0.7464926 0.5071930 0.70899268 0.98794839 0.45742096
 [4,] 0.003548722 0.1802593 0.1615858 0.26811666 0.85106955 0.79418897
 [5,] 0.262946911 0.5545452 0.3542665 0.03499987 0.07751327 0.95024571
 [6,] 0.324979464 0.5617152 0.3767844 0.40179265 0.26776372 0.54135361
 [7,] 0.622638935 0.1296170 0.4159080 0.04488852 0.59169089 0.45936268
 [8,] 0.118732307 0.5340533 0.6795494 0.96684736 0.28750470 0.07005899
 [9,] 0.733660081 0.9825798 0.1018399 0.01974215 0.65805039 0.58552912
[10,] 0.039080997 0.3026420 0.5166428 0.32624773 0.13347826 0.35099209
      [,7]      [,8]        [,9]       [,10]     
 [1,] 0.4361059 0.438944685 0.42980199 0.01005201
 [2,] 0.5854412 0.056552321 0.05502361 0.84160455
 [3,] 0.8007255 0.612099773 0.17579378 0.27279581
 [4,] 0.4221502 0.603443788 0.23405934 0.23172384
 [5,] 0.6641080 0.775671734 0.70373065 0.47395619
 [6,] 0.8696630 0.298280690 0.59194178 0.16926407
 [7,] 0.9651222 0.860343546 0.89873455 0.42812996
 [8,] 0.9454620 0.538394625 0.47723770 0.66889826
 [9,] 0.1830504 0.699020421 0.05117424 0.32957337
[10,] 0.4242837 0.005065657 0.08016398 0.14428638

In [37]:
#Definimos b vector de números aleatorios
set.seed(123)
b<-c(runif(n = n, min = -100, max = 100))

In [38]:
#Función
x_sel <- sel_solver(A,b,TOL,maxsweep)

**Y vemos que para este caso Comp=Ax vuelve a ser diferente del vector b.**

In [39]:
#Comprobamos si la solución x es correcta
Comp<-A%*%x_sel
all(Comp==b)

[1] FALSE

In [40]:
#Verificamos que ninguno de los elementos de tamaño 10 coinciden
length(which(Comp != b))

[1] 10

**Notamos que los elementos de ambos vectores vuelven a coincidir respecto a su signo y las diferencias entre cada entrada se hacen más pequeñas.**

In [42]:
Comp
b

[,1]      
 [1,] -46.240477
 [2,]  50.092697
 [3,] -30.286978
 [4,]  69.009522
 [5,]  87.828847
 [6,] -66.945451
 [7,]  15.322677
 [8,]  92.637391
 [9,]  27.256883
[10,]   5.875627

[1] -42.484496  57.661027 -18.204616  76.603481  88.093457 -90.888700
 [7]   5.621098  78.483809  10.287003  -8.677053

Con la comprobación, vemos que las entradas de Comp=Ax se acercan más a las del vector de b. Sin embargo, las diferencias siguen siendo relativamente grandes.

In [45]:
#Calculamos el promedio del valor absoluto de las diferencias entre ambos vectores
mean((abs(Comp-b)))

[1] 11.05862

**Por último reduciremos la dimensión de A de $2 \times 2$**

In [46]:
w <- 1
x <- 5
y <- 3
z <- 4

n<-2

#Definimos A matriz pseudo-aleatoria de números entre 0 y 1 con 16 decimales 
A<-mlsjunkgenm(nrow = n, ncol = n, w = w, x = x, y = y, z = z, round = 16)
TOL<-10**-8
maxsweep<-20
A

[,1]      [,2]       
[1,] 0.8470940 0.436393491
[2,] 0.7461152 0.003548722

In [47]:
#Definimos b vector de números aleatorios
set.seed(123)
b<-c(runif(n = n, min = -100, max = 100))

In [48]:
#Función
x_sel <- sel_solver(A,b,TOL,maxsweep)

**Y vemos que para este caso Comp=Ax vuelve a ser diferente del vector b.**

In [49]:
#Comprobamos si la solución x es correcta
Comp<-A%*%x_sel
all(Comp==b)

[1] FALSE

**Sin embargo, la primera entrada de ambos vectores sí coincide**

In [60]:
#Al comparar Comp y b, sí coincide la primera entrada pero la segunda es distinta
which(Comp != b)

[1] 2

In [51]:
Comp
b

[,1]     
[1,] -42.48450
[2,]  57.66103

[1] -42.48450  57.66103

**Bajo un redondeo a 13 cifras, ambos vectores coinciden**

In [58]:
#Volvemos a hacer la comparación y vemos que todas las entradas coinciden a 13 cifras
length(which(round(Comp,13) != round(b,13)))

[1] 0

In [62]:
#Calculamos el promedio del valor absoluto de las diferencias entre ambos vectores
(abs(Comp-b))

[,1]        
[1,] 0.000000e+00
[2,] 7.105427e-15

**Principales hallazos del test 6**

* La función parece no aproximar de manera precisa la solución para SEL propuestos con A matrices y lados derechos de números pseudo-aleatorios.

**4. Resumen detallado de posibles puntos faltantes en implementación y Sugerencias para resolver los puntos anteriores**

* Se sugiere complementar la descripción de los argumentos de entrada especificando que A tiene que ser una matriz de números reales de dimensión nxm. Además, mencionar que A es una matriz de coeficientes del sistema (en lugar de incógnitas) para SEL. Y se recomienda complementar la descripción de b: "#    b (float): vector de igualdad o lado derecho del sistema"
* Se sugiere complementar la descripción del argumento de salida especificando que x es de tamaño n.
* Necesita revisarse el caso de matrices con todos sus elementos iguales a una constante pues no encuentra la SVD.
* Es necesario verificar si existen errores de aritmética de máquina al calcular los valores de x que resuelven SEL para matrices y lados derechos con números pseudo-aleatorios pues no se satisfizo la comprobación de que Ax sea igual al valor b propuesto.