# Revisión de código Eliminación por bloques basada en solver linear que usa SVD 
## (parte 1-Funcion bloques)
*ver parte 2 al fondo*  
**Fecha:** 12 de Abril de 2020 

**Responsable de revisión:** Javier Valencia

**Código revisado**

In [20]:
bloques<-function(A,b,corte) {
  #Función que genera los bloques de la matriz A y el vector respuesta b
  #Args: A- matriz inicial(n*n)
  #      b- Solución de Ax = b , (nx1)
  #      corte - tamaño del bloque 
  #Returns: lista con la matriz A dividida en 4 bloques: A11,A12, A21, A22 y el vector b
  #         dividido en 2 bloques b1, b2

  a11 <- A[c(1:corte),c(1:corte)]
  a12 <- A[c(1:corte),c((corte+1):dim(A)[2])]
  a21 <- A[c((corte+1):dim(A)[1]),c(1:corte)]
  a22 <- A[c((corte+1):dim(A)[1]),c((corte+1):dim(A)[2])]

  b1 <- b[1:(corte)]
  b2 <- b[((corte)+1):length(b)]

  list(A11 = a11,A12 =a12, A21=a21, A22=a22, b1 = b1, b2 = b2)
} 

In [21]:
#Prueba
A = matrix(sample(0:50,7*7,replace=TRUE), c(7,7)) 
b = c(1:dim(A)[1])
A
b
bloques(A,b,4)

[,1] [,2] [,3] [,4] [,5] [,6] [,7]
[1,] 17   20   37    9   36   27   33  
[2,]  7   24   19   37   45   34   18  
[3,] 37   16   27   31   42    5   32  
[4,] 39   21   20   46   42   49    3  
[5,]  4   34    0   40   42   31   27  
[6,] 13   49   38   12   37   50   25  
[7,]  9   35   18   40   19   21   33

[1] 1 2 3 4 5 6 7

$A11
     [,1] [,2] [,3] [,4]
[1,]   17   20   37    9
[2,]    7   24   19   37
[3,]   37   16   27   31
[4,]   39   21   20   46

$A12
     [,1] [,2] [,3]
[1,]   36   27   33
[2,]   45   34   18
[3,]   42    5   32
[4,]   42   49    3

$A21
     [,1] [,2] [,3] [,4]
[1,]    4   34    0   40
[2,]   13   49   38   12
[3,]    9   35   18   40

$A22
     [,1] [,2] [,3]
[1,]   42   31   27
[2,]   37   50   25
[3,]   19   21   33

$b1
[1] 1 2 3 4

$b2
[1] 5 6 7

[1] "1"


**1.Sobre la documentación del código/de la función**

¿Se encuentran presentes en la implementación los siguientes elementos? Por favor, ingrese explicaciones detalladas.

**a) Descripción concisa y breve de lo que hace el código/la función**

Sí, la documentación de la función "bloques" explica lo que hace, en este caso divide una matriz cuadrada en 4 bloques

**b) Descripción de sus argumentos de entrada, su significado y rango de valores que pueden tomar**

Se sugiere detallar que el valor de corte debe estar en siguiente rango de valores "0<corte<n".
Debe de estar entre 1 y n el valor del rango de la matriz

**c) Descripción de los tipos de argumentos de entrada y de salida (por ejemplo, valores enteros, reales, strings, dataframe, matrices, etc)**

Es completa la documentación, la funcion regresa una lista con las 4 partes de la matriz A y las 2 partes del vector b

**d) Descripción de la salida de la función, su significado y valores/objetos que deben regresa**

La documentación de salida esta completa, especifica los argumentos de salida de la función y su significado


**2. Cumplimiento de objetivos del código/de la función**

Por favor, ingrese explicaciones detalladas.

**a) ¿El código cumple los objetivos para los que fue diseñado?**

Sí, la función cumple su objetivo regresando una lista con las particiones de la matriz A y del vector b

**b) ¿La salida de la función regresa una lista con 4 matrices y 2 vectores?**
Sí


**3. Pruebas**

Ocupe la presente sección para hacer diseño de pruebas variando los parámetros que recibe el código la función en diferentes rangos para evaluae su comportamiento y/o detectar posibles fallos

**Test 1 cambiando el parametro de corte para valores pares e impares**

**Objetivo del test:** Revisar si la función realiza su trabajo para cortes de numeros pares o impares.

**Implementación del test:**

In [92]:
#Prueba para valor de parametro de corte 
A = matrix(c(0:24), nrow=5,ncol=5) 
b = c(1:dim(A)[1])
A
b
n<-1
#Probamos con un valor par corte=2n
corte<-2
cat("Prueba corte con valor par (2n):\ncorte=",corte)
l<-bloques(A,b,corte)
l
#Probamos con un valor impar corte=2n+1
corte<-3
cat("Prueba corte con valor impar (2n+1):\ncorte=",corte)
l<-bloques(A,b,corte)
l

[,1] [,2] [,3] [,4] [,5]
[1,] 0    5    10   15   20  
[2,] 1    6    11   16   21  
[3,] 2    7    12   17   22  
[4,] 3    8    13   18   23  
[5,] 4    9    14   19   24

[1] 1 2 3 4 5

Prueba corte con valor par (2n):
corte= 2

$A11
     [,1] [,2]
[1,]    0    5
[2,]    1    6

$A12
     [,1] [,2] [,3]
[1,]   10   15   20
[2,]   11   16   21

$A21
     [,1] [,2]
[1,]    2    7
[2,]    3    8
[3,]    4    9

$A22
     [,1] [,2] [,3]
[1,]   12   17   22
[2,]   13   18   23
[3,]   14   19   24

$b1
[1] 1 2

$b2
[1] 3 4 5

Prueba corte con valor impar (2n+1):
corte= 3

$A11
     [,1] [,2] [,3]
[1,]    0    5   10
[2,]    1    6   11
[3,]    2    7   12

$A12
     [,1] [,2]
[1,]   15   20
[2,]   16   21
[3,]   17   22

$A21
     [,1] [,2] [,3]
[1,]    3    8   13
[2,]    4    9   14

$A22
     [,1] [,2]
[1,]   18   23
[2,]   19   24

$b1
[1] 1 2 3

$b2
[1] 4 5

**Test 2 valores que generan errores en la funcion**

In [91]:
#Probamos con un valor corte mas grande que el rango de la matriz
corte<-5
cat("Prueba corte con valor mas grande que el rango de la matriz(corte>n):\ncorte=",corte)
l<-bloques(A,b,corte)
l

Prueba corte con valor mas grande que el rango de la matriz(corte>n):
corte= 5

ERROR: Error in A[c(1:corte), c((corte + 1):dim(A)[2])]: subscript out of bounds


In [85]:
#Probamos con un valor corte mas grande que el rango de la matriz
corte<-0
cat("Prueba corte con valor mas grande que el rango de la matriz(corte>n):\ncorte=",corte)
l<-bloques(A,b,corte)
l

Prueba corte con valor mas grande que el rango de la matriz(corte>n):
corte= 0

$A11
[1] 0

$A12
[1]  0  5 10 15 20

$A21
[1] 0 1 2 3 4

$A22
     [,1] [,2] [,3] [,4] [,5]
[1,]    0    5   10   15   20
[2,]    1    6   11   16   21
[3,]    2    7   12   17   22
[4,]    3    8   13   18   23
[5,]    4    9   14   19   24

$b1
[1] 1

$b2
[1] 1 2 3 4 5

In [86]:
#Probamos con un valor corte mas grande que el rango de la matriz
corte<--1
cat("Prueba corte con valor mas grande que el rango de la matriz(corte>n):\ncorte=",corte)
l<-bloques(A,b,corte)
l

Prueba corte con valor mas grande que el rango de la matriz(corte>n):
corte= -1

ERROR: Error in A[c(1:corte), c(1:corte)]: only 0's may be mixed with negative subscripts


Principales hallazos del test:   
**Rango de error de parametro corte**  
* Hallazgo 1: La función no funciona si el valor de corte no esta en el rango 0<corte<n, n siendo el rango de la matriz A
* Hallazgo 2: La función funciona para corte=0


**4. Resumen detallado de posibles puntos faltantes en implementación**
* Añadir a la documentación de la función bloques el rango permitido para el parametro de corte.
* Los parametros matriz A y vector b no causan errores debido a sus valores. Por lo que no se sugiere algun cambio referente a ellos
**Sugerencias para resolver los puntos anteriores**
* se sugiere poner en la documentación el rango permitido para el parametro de corte.

# Revisión de código Eliminación por bloques basada en solver linear que usa SVD
## (parte 2-funcion eliminacion_bloques)

**Fecha:** 13 de Abril de 2020 

**Responsable de revisión:** Javier Valencia

**Código revisado: se revisa la función eliminacion_bloques, pero esta se apoya de las otras funciones en el codigo**

In [110]:
install.packages("matrixcalc")
library("matrixcalc")
#install.packages("tictoc")
devtools::install_github("collectivemedia/tictoc")
library(tictoc)

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)




✔  checking for file ‘/tmp/Rtmp8RzAQR/remotes266b02aef9/collectivemedia-tictoc-211fe59/DESCRIPTION’
─  preparing ‘tictoc’:
✔  checking DESCRIPTION meta-information
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘tictoc_1.0.tar.gz’
   


Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)



### Código del cual depende nuestra función que ya fue revisado y corregido

In [108]:
indices <- function(n) {
  # Crea una lista de tamaño (n-1)n/2 con pares de índices de la siguiente
  #  manera: (1,2),..,(1,n),(2,3),..,(2,n),...,(n-1,n)
  # Args: 
  #    n: número entero postivo 
  #       se refiere al número de columnas
  #Returns:
  #    lista con pares de índices
  a <- NULL
  b <- NULL
  indices <- NULL
  for (i in 1:(n-1)){
    a <- append(a,rep(i,n-i))
    b <- append(b,seq(i+1,n))    
  }
  for(i in 1:round(n*(n-1)/2))
    indices[[i]] <- list(c(a[i], b[i]))
  indices
}

ortogonal <- function(u,v,TOL=10^-8){
  # Verifica si dos vectores son ortogonales, arrojando un 1 si lo es, y un 0 si no lo es.
  # Args: 
  # u, v como vectores de la misma dimensión.Y un valor real de tolerancia TOL(10^-8).
  # Nota: Se sugiere una TOL mayor a 10^-32.
  # Returns: 
  # Valor booleano 0 (no son ortongoales), 1 (son ortogonales)
  
  nu = norm(u,type ="2")
  nv = norm(v,type ="2") 
  
  if ( nu < TOL | nv < TOL){
    ret<-0
  } else{ 
    
    if( (u%*%v)  /(nu*nv) < TOL   ){
      ret<-1
    }
    else{
      ret<-0
    }       
  }
  ret
}

signo<-function(x) {
  # Indica el signo de un número x
  # Args: 
  #    x (numeric): número a revisar
  # Returns:
  #    1 si el número es positivo o cero
  #    -1 si el número es negativo
  
  ifelse(x<0,-1,1)
}


solver <- function(U,S,V,b){
  # Construye la solución de un sistema de ecuaciones a partir de matrices 
  # U, S, V, y vector b. Se asume que S es diagonal. 
  # Para ello resuelve S d = U^Tb, para construir x=Vd.
  # Notas:
  # 1) Se utilizó la función backsolve para resolver el sistema triangular.
  # 2) Al ser S diagonal, es indistinto si usar un solver para matrices traingulares inferiores o superiores.
  # Args: 
  #  	    U (mxm),V(nxn), S(mxn) matriz diagonal y b (m) un vector.
  # Returns: 
  #      x vector (m)
  d = backsolve(S, t(U)%*%b)
  x = V%*%d
  return(x)
}


svd_jacobi_aprox <- function(A,TOL,maxsweep){
  #Función que devuelve una lista con las matrices U, S, V que aproximan númericamente a A 
  #por medio del método de One-sided Jacobi 
  # Args: 
  #    A: matriz a la que se le calculará su SVD
  #    TOL (numeric): controla la convergencia del método
  #    maxsweep (numeric): número máximo de sweeps 
  # Returns: 
  #   lista con matrices U, S, V
  
  #dimensiones
  n<-dim(A)[2] #numero de columnas
  m<-dim(A)[1] #numero de filas
  nmax<-n*(n-1)/2 
  
  #inicialza valores del ciclo
  ak<-A
  vk<-diag(n)
  sig <- NULL
  uk <- ak
  num_col_ortogonal<-0
  k<-0
  
  while(k<=maxsweep & num_col_ortogonal<nmax){
    num_col_ortogonal<-0
    
    ind <- indices(n)
    for(i in 1:nmax){
      col_j<-ak[,ind[[i]][[1]][2]]
      col_i<-ak[,ind[[i]][[1]][1]]
      
      #comprueba ortogonalidad  
      if(ortogonal(col_i,col_j,TOL)==1){
        num_col_ortogonal<-num_col_ortogonal+1
      }
      else{
        #calcula coeficientes de la matriz
        a<-col_i%*%col_i#sum(col_i*col_i) #cambio
        b<- col_j%*%col_j #sum(col_j*col_j) #cambio
        c<-col_i%*%col_j
        
        #calcula la rotacion givens que diagonaliza
        epsilon<-(b-a)/(2*c)
        t<-signo(epsilon)/(abs(epsilon)+sqrt(1+epsilon**2))
        cs<-1/sqrt(1+t**2)
        sn<-cs*t
        
        #actualiza las columnas de la matriz ak
        
        temp<-ak[,ind[[i]][[1]][1]] #cambio
        ak[,ind[[i]][[1]][1]]<-c(cs)*temp-c(sn)*ak[,ind[[i]][[1]][2]]#cambio
        ak[,ind[[i]][[1]][2]]<-c(sn)*temp+c(cs)*ak[,ind[[i]][[1]][2]]#cambio
        
        # for(l in seq(1,m)){ #cambio
        #   temp<-ak[l,ind[[i]][[1]][1]] #cambio
        #   ak[l,ind[[i]][[1]][1]]<-cs*temp-sn*ak[l,ind[[i]][[1]][2]] #cambio
        #   ak[l,ind[[i]][[1]][2]]<-sn*temp+cs*ak[l,ind[[i]][[1]][2]] #cambio
        # }
        
        #actualiza las columnas de la matriz vk
        temp<-vk[,ind[[i]][[1]][1]] #cambio
        vk[,ind[[i]][[1]][1]]<-c(cs)*temp-c(sn)*vk[,ind[[i]][[1]][2]] #cambio
        vk[,ind[[i]][[1]][2]]<-c(sn)*temp+c(cs)*vk[,ind[[i]][[1]][2]] #cambio
        
        # for(l in seq(1,n)){ #cambio
        #   temp<-vk[l,ind[[i]][[1]][1]] #cambio
        #   vk[l,ind[[i]][[1]][1]]<-cs*temp-sn*vk[l,ind[[i]][[1]][2]] #cambio
        #   vk[l,ind[[i]][[1]][2]]<-sn*temp+cs*vk[l,ind[[i]][[1]][2]] #cambio
        #   
        # }
      }
    }
    k<-k+1
  }
  #Obtener sigma
  sig<-apply(ak, 2, function(x){norm(x,"2")}) #cambio
  #for(i in 1:n){ #cambio
  #  sig<- append(sig,norm(ak[,i],type ="2")) #cambio
  #} #cambio
  
  #Obtener U
  #nrow_ak<-m
  #uk<-apply(ak, 2, function(x){x/norm(x,"2")})*(sig<TOL)
    for(i in 1:n){
      if (sig[i]<TOL){
        
        uk[,i]<-0
        
      } else{
        uk[,i] <- ak[,i]/sig[i]
      }
    }
  
  # Indices de sigma ordenada en forma decreciente para ordenar V,S,U
  index <- order(sig,decreasing = TRUE)
  vk <- vk[,index]
  S <- diag(sig[index])
  uk <- uk[,index]
  
  list(S = S, U = uk, V= vk)
}

# n =10**3
# A = matrix(rnorm(n**2), ncol=n)
# 
# descom <- svd_jacobi_aprox(A,10**-8,1)
# 
# S<-descom$S
# U<-descom$U
# V<-descom$V
# 
# A_svd <- U%*%S%*%t(V)
# 
# norm(A-A_svd,"2")



sel_solver<-function(A,b,TOL=10**-8,maxsweep=20){
  #Función resuelve un sistema de ecuaciones lineales (SEL) utilizando la descomposición SVD
  #por medio del método de One-sided Jacobi 
  #El SEL es de la forma Ax=b
  # Args: 
  #    A (float): matriz de incógnitas del SEL
  #    b (float): vector de igualdada del sistema
  #    TOL (numeric): controla la convergencia del método
  #    maxsweep (int): número máximo de sweeps 
  #Returns: x (float): vector solución 
  
  svd<-svd_jacobi_aprox(A,TOL,maxsweep)
  x<-solver(svd$U,svd$S,svd$V,b)
  x
}

bloques<-function(A,b,corte) {
  #Función que genera los bloques de la matriz A y el vector respuesta b
  #Args: A- matriz inicial(n*n)
  #      b- Solución de Ax = b , (nx1)
  #      corte - tamaño del bloque 
  #Returns: lista con la matriz A dividida en 4 bloques: A11,A12, A21, A22 y el vector b
  #         dividido en 2 bloques b1, b2
  
  a11 <- A[c(1:corte),c(1:corte)]
  a12 <- A[c(1:corte),c((corte+1):dim(A)[2])]
  a21 <- A[c((corte+1):dim(A)[1]),c(1:corte)]
  a22 <- A[c((corte+1):dim(A)[1]),c((corte+1):dim(A)[2])]
  
  b1 <- b[1:(corte)]
  b2 <- b[((corte)+1):length(b)]
  
  list(A11 = a11,A12 =a12, A21=a21, A22=a22, b1 = b1, b2 = b2)
}

## función a revisar: eliminacion_bloques

In [103]:
eliminacion_bloques <- function(A,b,corte, TOL, maxsweep){
  #Función que realiza el método de eliminación por bloques
  #Args: A- matriz inicial(n*n)
  #      b- Solución de Ax = b , (nx1)
  #      corte - tamaño del bloque 
  #      TOL (numeric): controla la convergencia del método
  #      maxsweep (numeric): número máximo de sweeps 
  #Returns: x: vector
  
  bloq = bloques(A,b,corte)
  if(is.singular.matrix(A,TOL) ==FALSE & is.singular.matrix(bloq$A11,TOL) == FALSE){
    
    
    svd<-svd_jacobi_aprox(bloq$A11,TOL,maxsweep) #cambio
    
    print("obtenemos y")
    #y = sel_solver(bloq$A11,bloq$b1,TOL, maxsweep) #cambio
    y <-solver(svd$U,svd$S,svd$V,bloq$b1) #cambio
    
    #Y= bloq$A12 #cambio
    #for(i in 1:dim(bloq$A12)[2]){ #cambio
    #  Y[,i] = sel_solver(bloq$A11,bloq$A12[,i],TOL, maxsweep) #cambio
    #} #cambio
    print("obtenemos Y mayuscula") #cambio
    #Y = sel_solver(bloq$A11,bloq$A12,TOL, maxsweep) #cambio
    Y <-solver(svd$U,svd$S,svd$V,bloq$A12) #cambio
    
    print("obtenemos S")
    S = bloq$A22 - bloq$A21%*%Y 
    print("obtenemos b_hat")
    b_hat = bloq$b2-bloq$A21%*%y 
    print("obtenemos x_2")
    x_2 = sel_solver(S,b_hat,TOL, maxsweep)
    print("obtenemos  b_hat2")
    b_hat2 = bloq$b1 -bloq$A12%*%x_2
    print("obtenemos  x_1")
    #x_1 = sel_solver(bloq$A11,b_hat2,TOL, maxsweep) #cambio
    x_1 <- solver(svd$U,svd$S,svd$V,b_hat2) #cambio
    print("obtenemos  x")
    x <- c(x_1,x_2)
    x
  }else{
    print("Singularidad de las matrices involucradas; no hay solucion")
  }
    
}

**1.Sobre la documentación del código/de la función**

¿Se encuentran presentes en la implementación los siguientes elementos? Por favor, ingrese explicaciones detalladas.

**a) Descripción concisa y breve de lo que hace el código/la función**

La documentación inicial de la función "eliminacion_bloques" es detallada, describe los  argumentos de entrada, de salida y el objetivo de la función.

**b) Descripción de sus argumentos de entrada, su significado y rango de valores que pueden tomar**
Los argumentos de entrada, y salida estan descritos pero no hay un rango de valores que podrían tomar en los parametros de "corte", "TOL" y "maxsweep"

**c) Descripción de los tipos de argumentos de entrada y de salida (por ejemplo, valores enteros, reales, strings, dataframe, matrices, etc)**

Los argumentos de salida estan correctamente tipificados, los argumentos de entrada como corte y maxsweep falta especificar que son enteros, para TOL sería un double

**d) Descripción de la salida de la función, su significado y valores/objetos que deben regresa**

La documentación de salida esta completa, especifica los argumentos de salida de la función y su significado


**2. Cumplimiento de objetivos del código/de la función**

El codigo cumple su objetivo al resolver un sistema de ecuaciones siempre y cuando los argumentos de entrada cumplan con los supuestos establecidos: A tiene que ser una matriz cuadrada y no singular. Por otro lado, si no se cumplen algunos de estos supuestos el codigo nos indica que el sistema de ecuaciones no tiene  solución. 
El codigo deja de ser funcional para matrices de orden de $10^4$ en adelante, ya que el empo necesario para ejecutarlo se incrementa en gran medida. 

**a) ¿El código cumple los objetivos para los que fue diseñado?**

Sí, la función cumple su objetivo regresa la solucion para un sistema de ecuaciones si este tiene solución y cumple con los supuestos mencionaodos en el punto aterior, de lo contrario nos ñindica que el sistema de ecuaciones no tiene solucion.

**b) ¿La salida de la función regresa un vector x?**
Sí, si el sistema tiene solucion


**3. Pruebas**

Ocupe la presente sección para hacer diseño de pruebas variando los parámetros que recibe el código la función en diferentes rangos para evaluae su comportamiento y/o detectar posibles fallos

**Test 1 probando diferentes tamaños de Matrices**

**Objetivo del test:** Revisar si la función realiza su trabajo para matrices de diferentes tamaños y el tiempo que toma.
Nota: Para implementar las pruebas usé la libreria (tictoc) para medir el tiempo  

**Implementación del test:**

In [112]:
#prueba con Matriz pequeña 
print("Prueba con una matriz pequeña A (n*n), donde n=10^2:")
tic("Tiempo de prueba_matriz_chica")
n= 10**2

A = matrix(rnorm(n**2), ncol=n)
b = matrix(rnorm(n), ncol=1)
TOL = 10**-8
maxsweep= 1
corte = n/2
x<-eliminacion_bloques(A,b,corte, TOL, maxsweep)

norm(A%*%x-b,"2")/norm(b,"2")
toc()

[1] "Prueba con una matriz pequeña A (n*n), donde n=10^2:"
[1] "obtenemos y"
[1] "obtenemos Y mayuscula"
[1] "obtenemos S"
[1] "obtenemos b_hat"
[1] "obtenemos x_2"
[1] "obtenemos  b_hat2"
[1] "obtenemos  x_1"
[1] "obtenemos  x"


[1] 1.355227

Tiempo de prueba_matriz_chica: 0.498 sec elapsed


**Prueba 2: Matriz de mediano tamaño**  
Se corrió el codigo en Google Colab con una matriz de $10^{3}X10^{3}$ debido a que el programa utiliza muchos recursos.
Se puede reproducir este test haciendo click en la siguiente liga: [google colab](https://colab.research.google.com/drive/1uOUndB7HabictLo1p6Ak1WrU1INrC5Bq) 
![image](../docs/images/test_elim_bloques.png)
Tiempo de prueba_matriz_mediana: 10 min aprox

**Prueba 3: Matriz de tamaño grande**
Se intentó correr el codigo desde Google Colab para una matriz de 10^4 pero el tiempo de ejecucion fue tan largo que me desconectó de la sesión que tenía 

Principales hallazos del test:   
**Tamaño de las matrices **  
* Hallazgo 1: El codigo funciona adecuadamente para matrices chicas n=10^2, es lento pero funcional para matrices medianas n=10^3, y no es funcional para matrices grandes n=10^4 en adelante

**Test 2 probando diferentes valores de los argumentos de entrada**

**Objetivo del test:** Revisar si la función realiza su trabajo variando los parametros de TOL, maxsweep y corte

**Implementación del test:**

In [117]:
#prueba cambiando TOL
print("Prueba con una matriz pequeña A (n*n) y TOL muy chica")
tic("Tiempo de prueba")
n= 10**2

A = matrix(rnorm(n**2), ncol=n)
b = matrix(rnorm(n), ncol=1)
TOL = 10**-322
maxsweep= 1
corte = n/2
x<-eliminacion_bloques(A,b,corte, TOL, maxsweep)

norm(A%*%x-b,"2")/norm(b,"2")
toc()

[1] "Prueba con una matriz pequeña A (n*n), donde n=10^2:"
[1] "obtenemos y"
[1] "obtenemos Y mayuscula"
[1] "obtenemos S"
[1] "obtenemos b_hat"
[1] "obtenemos x_2"
[1] "obtenemos  b_hat2"
[1] "obtenemos  x_1"
[1] "obtenemos  x"


[1] 1.414768

Tiempo de prueba_matriz_chica: 0.512 sec elapsed


In [119]:
#prueba cambiando maxsweep=50
print("Prueba con una matriz pequeña A (n*n) y max sweep grande=50")
tic("Tiempo de prueba_maxsweep=50")
n= 10**2

A = matrix(rnorm(n**2), ncol=n)
b = matrix(rnorm(n), ncol=1)
TOL = 10**-8
maxsweep= 50
corte = n/2
x<-eliminacion_bloques(A,b,corte, TOL, maxsweep)

norm(A%*%x-b,"2")/norm(b,"2")
toc()
#prueba cambiando maxsweep=20
print("Prueba con una matriz pequeña A (n*n) y max sweep =20")
tic("Tiempo de prueba_maxsweep=20")
n= 10**2

A = matrix(rnorm(n**2), ncol=n)
b = matrix(rnorm(n), ncol=1)
TOL = 10**-8
maxsweep= 20
corte = n/2
x<-eliminacion_bloques(A,b,corte, TOL, maxsweep)

norm(A%*%x-b,"2")/norm(b,"2")
toc()

[1] "Prueba con una matriz pequeña A (n*n) y max sweep grande=50"
[1] "obtenemos y"
[1] "obtenemos Y mayuscula"
[1] "obtenemos S"
[1] "obtenemos b_hat"
[1] "obtenemos x_2"
[1] "obtenemos  b_hat2"
[1] "obtenemos  x_1"
[1] "obtenemos  x"


[1] 1.277067

Tiempo de prueba_maxsweep=50: 10.494 sec elapsed
[1] "Prueba con una matriz pequeña A (n*n) y max sweep =20"
[1] "obtenemos y"
[1] "obtenemos Y mayuscula"
[1] "obtenemos S"
[1] "obtenemos b_hat"
[1] "obtenemos x_2"
[1] "obtenemos  b_hat2"
[1] "obtenemos  x_1"
[1] "obtenemos  x"


[1] 1.11788

Tiempo de prueba_maxsweep=20: 4.722 sec elapsed


In [123]:
#prueba cambiando corte n/4
print("Prueba con una matriz pequeña A (n*n) y corte=n/8")
tic("Tiempo de prueba_corte=n/8")
n= 10**2

A = matrix(rnorm(n**2), ncol=n)
b = matrix(rnorm(n), ncol=1)
TOL = 10**-8
maxsweep= 20
corte = n/4
x<-eliminacion_bloques(A,b,corte, TOL, maxsweep)

norm(A%*%x-b,"2")/norm(b,"2")
toc()
#prueba cambiando corte n/2
print("Prueba con una matriz pequeña A (n*n) y corte=n/8")
tic("Tiempo de prueba_corte=n/8")
n= 10**2

A = matrix(rnorm(n**2), ncol=n)
b = matrix(rnorm(n), ncol=1)
TOL = 10**-8
maxsweep= 20
corte = n/4
x<-eliminacion_bloques(A,b,corte, TOL, maxsweep)

norm(A%*%x-b,"2")/norm(b,"2")
toc()

[1] "Prueba con una matriz pequeña A (n*n) y corte=n/8"
[1] "obtenemos y"
[1] "obtenemos Y mayuscula"
[1] "obtenemos S"
[1] "obtenemos b_hat"
[1] "obtenemos x_2"
[1] "obtenemos  b_hat2"
[1] "obtenemos  x_1"
[1] "obtenemos  x"


[1] 1.446123

Tiempo de prueba_corte=n/8: 5.906 sec elapsed
[1] "Prueba con una matriz pequeña A (n*n) y corte=n/8"
[1] "obtenemos y"
[1] "obtenemos Y mayuscula"
[1] "obtenemos S"
[1] "obtenemos b_hat"
[1] "obtenemos x_2"
[1] "obtenemos  b_hat2"
[1] "obtenemos  x_1"
[1] "obtenemos  x"


[1] 2.346695

Tiempo de prueba_corte=n/8: 5.712 sec elapsed


Principales hallazos del test:   
**Otras causas de errores  
* Hallazgo 2: TOL no afecta el tiempo de ejecucion del algoritmo, pero puede hacer que la solucion del sistema de ecuaciones no sea la correcta
* Hallazgo 3: el parametro max sweep afecta el tiempo de ejecucion de la funcion a mayor maxsweep mas se tarda el codigo en ejecutarse
* Hallazgo 4: el parametro de corte no afecta en el tiempo de ejecucion

**4. Resumen detallado de posibles puntos faltantes en implementación**

* añadir en documentacion los rangos de valores permitidos para TOL, maxsweep, y corte
* añadir en documentación el tipo de los valores de TOL(double), max sweep (int), corte(int)

**Sugerencias para resolver los puntos anteriores**

* Para resolver el problema del tiempo de ejecución del código se sugiere que para matrices grandes n=10^4, en adelante, se pueden dividir las matrices A11, A12, A21, A22 nuevamente y paralelizar este codigo. Nota: esta sugerencia no es mandatoria ya que la implementación de esta puede entrar en conflicto con el deadline de entrega del examen.
